[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.81.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

#Additional redirects
#CV
[[redirects]]
  from = "https://lucabontempi.it/cv"
  to = "https://lucabontempi.com/cv"
  status = 302
  force = true

[[redirects]]
  from = "https://www.lucabontempi.it/cv"
  to = "https://lucabontempi.com/cv"
  status = 302
  force = true

[[redirects]]
  from = "https://lucabontempi.eu/cv"
  to = "https://lucabontempi.com/cv"
  status = 302
  force = true

[[redirects]]
  from = "https://www.lucabontempi.eu/cv"
  to = "https://lucabontempi.com/cv"
  status = 302
  force = true

[[redirects]]
  from = "https://bontempi.me/cv"
  to = "https://lucabontempi.com/cv"
  status = 302
  force = true

[[redirects]]
  from = "https://www.bontempi.me/cv"
  to = "https://lucabontempi.com/cv"
  status = 302
  force = true

#Il mercato informatico
[[redirects]]
  from = "https://lucabontempi.it/il_mercato_informatico/"
  to = "https://lucabontempi.com/il_mercato_informatico/"
  status = 302
  force = true

[[redirects]]
  from = "https://www.lucabontempi.it/il_mercato_informatico/"
  to = "https://lucabontempi.com/il_mercato_informatico/"
  status = 302
  force = true

[[redirects]]
  from = "https://lucabontempi.eu/il_mercato_informatico/"
  to = "https://lucabontempi.com/il_mercato_informatico/"
  status = 302
  force = true

[[redirects]]
  from = "https://www.lucabontempi.eu/il_mercato_informatico/"
  to = "https://lucabontempi.com/il_mercato_informatico/"
  status = 302
  force = true

[[redirects]]
  from = "https://lucabontempi.com/ilmercatoinformatico/"
  to = "https://lucabontempi.com/il_mercato_informatico/"
  status = 302
  force = true

[[redirects]]
  from = "https://www.lucabontempi.com/ilmercatoinformatico/"
  to = "https://lucabontempi.com/il_mercato_informatico/"
  status = 302
  force = true

[[redirects]]
  from = "https://lucabontempi.it/ilmercatoinformatico/"
  to = "https://lucabontempi.com/il_mercato_informatico/"
  status = 302
  force = true

[[redirects]]
  from = "https://www.lucabontempi.it/ilmercatoinformatico/"
  to = "https://lucabontempi.com/il_mercato_informatico/"
  status = 302
  force = true

[[redirects]]
  from = "https://lucabontempi.eu/ilmercatoinformatico/"
  to = "https://lucabontempi.com/il_mercato_informatico/"
  status = 302
  force = true

[[redirects]]
  from = "https://www.lucabontempi.eu/ilmercatoinformatico/"
  to = "https://lucabontempi.com/il_mercato_informatico/"
  status = 302
  force = true

# Fundamental Redirects
[[redirects]]
  from = "https://lucabontempi.it/*"
  to = "https://lucabontempi.com"
  status = 302
  force = true

[[redirects]]
  from = "https://www.lucabontempi.it/*"
  to = "https://lucabontempi.com"
  status = 302
  force = true

[[redirects]]
  from = "https://lucabontempi.eu/*"
  to = "https://lucabontempi.com"
  status = 302
  force = true

[[redirects]]
  from = "https://www.lucabontempi.eu/*"
  to = "https://lucabontempi.com"
  status = 302
  force = true

[[redirects]]
  from = "https://lucabontempi.netlify.app/*"
  to = "https://lucabontempi.com"
  status = 302
  force = true

[[redirects]]
  from = "https://bontempi.me/*"
  to = "https://lucabontempi.com"
  status = 302
  force = true

[[redirects]]
  from = "https://www.bontempi.me/*"
  to = "https://lucabontempi.com"
  status = 302
  force = true

[[redirects]]
  from = "https://bontemp.one/*"
  to = "https://lucabontempi.com"
  status = 302
  force = true

[[redirects]]
  from = "https://www.bontemp.one/*"
  to = "https://lucabontempi.com"
  status = 302
  force = true

[[redirects]]
  from = "https://bonte.lu/*"
  to = "https://lucabontempi.com"
  status = 302
  force = true

[[redirects]]
  from = "https://www.bonte.lu/*"
  to = "https://lucabontempi.com"
  status = 302
  force = true