[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.81.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

[[redirects]]
  from = "https://lucabontempi.it/*"
  to = "https://lucabontempi.com"
  status = 302
  force = true

[[redirects]]
  from = "https://www.lucabontempi.it/*"
  to = "https://lucabontempi.com"
  status = 302
  force = true

[[redirects]]
  from = "https://lucabontempi.eu/*"
  to = "https://lucabontempi.com"
  status = 302
  force = true

[[redirects]]
  from = "https://www.lucabontempi.eu/*"
  to = "https://lucabontempi.com"
  status = 302
  force = true

[[redirects]]
  from = "https://lucabontempi.netlify.app/*"
  to = "https://lucabontempi.com"
  status = 302
  force = true

#Additional redirects
 
 #CV
[[redirects]]
  from = "https://lucabontempi.it/cv"
  to = "https://lucabontempi.com/cv"
  status = 302
  force = true

[[redirects]]
  from = "https://www.lucabontempi.it/cv"
  to = "https://lucabontempi.com/cv"
  status = 302
  force = true

[[redirects]]
  from = "https://lucabontempi.eu/cv"
  to = "https://lucabontempi.com/cv"
  status = 302
  force = true

[[redirects]]
  from = "https://www.lucabontempi.eu/cv"
  to = "https://lucabontempi.com/cv"
  status = 302
  force = true
