[build]
  command = "hugo --gc --minify -b /"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.81.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b /"

[context.branch-deploy]
  command = "hugo --gc --minify -b /"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true