backend:
  name: git-gateway
  branch: main # Sostituisci con 'master' se il tuo branch principale si chiama così

media_folder: "static/blog" # Dove vengono salvate le immagini caricate
public_folder: "/blog"      # Come le immagini vengono referenziate nei file markdown

collections:
  - name: "blog"
    label: "Articoli Blog"
    folder: "content/blog" # La cartella dove Hugo salva i tuoi post
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Bozza", name: "draft", widget: "boolean", default: true}
      - {label: "Corpo dell'articolo", name: "body", widget: "markdown"}